# Generated by Django 5.1.4 on 2024-12-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswamagang',
            name='pembimbing',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
