# Generated by Django 5.1.4 on 2024-12-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0002_mahasiswamagang_pembimbing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswamagang',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
