# Generated by Django 5.1.4 on 2024-12-19 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0003_alter_mahasiswamagang_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswamagang',
            name='nim',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mahasiswamagang',
            name='no_hp',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Masukkan nomor HP dalam format: '+628123456789'. Maksimal 15 digit.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
